### ISSUE TITLE
Implerentar reinicio de trivia

### ISSUE THREAD

**Issue by fabMen24** [HansUrpay/Mi_Trivia#2]
En este caso se podría implementar un clear para limpiar la consolar y agregar la opción reiniciar la trivia o terminar el juego.
![image](https://user-images.githubusercontent.com/89615939/190501682-aa2e85df-b9b6-40b9-a4fb-3b1e2f5a12e4.png)

**Comment by HansUrpay** [comment]
Se agregó opción de reinicio de trivia para volver a jugar o finalizar la partida

**Comment by HansUrpay** [comment]
Se agregó la funcion clean para limpiar pantalla y mantener un mejor orden
